# Generated by Django 5.2.13 on 2026-04-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em progresso'), ('done', 'Completo'), ('error', 'Erro')], default='pending', max_length=20)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'Fonte A'), ('B', 'Fonte B')], max_length=1)),
                ('data_type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('api', 'API REST'), ('sql', 'Banco SQL')], max_length=10)),
                ('origin', models.CharField(choices=[('upload', 'Upload de arquivo'), ('url', 'URL remota'), ('endpoint', 'URL do endpoint'), ('database', 'Banco de dados')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('connection_string', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='sources.integration')),
            ],
            options={
                'unique_together': {('integration', 'label')},
            },
        ),
    ]
