# Generated by Django 5.2.13 on 2026-04-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_source_a', models.CharField(max_length=255)),
                ('key_source_b', models.CharField(max_length=255)),
                ('join_type', models.CharField(choices=[('inner', 'Inner Join'), ('left', 'Left Join'), ('right', 'Right Join'), ('outer', 'Outer Join')], default='inner', max_length=10)),
                ('columns_to_keep', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_config', to='sources.integration')),
            ],
        ),
    ]
