# Generated by Django 5.2.13 on 2026-04-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_joinconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
